language: generic
sudo: required
services:
  - docker

before_install:
 - docker build -t dannyjoeanto/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true dannyjoeanto/docker-react npm run test